development:
  adapter: postgresql
  encoding: unicode
  database: splitfare_dev
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: splitfare_test
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: splitfare_prod
  pool: 5
  timeout: 5000
